---
title: "Bylaws: Excuses Outlined"
format: html
---

As per pages 8 & 9 of our bylaws:

“Excused Absence

1.  An absence may be excused by the Executive Council for a valid reason.

2.  An absence shall be explained to the Executive Council, in writing, via the Vice President–Administration at least three days prior to the event.

3.  Valid reasons for excused absences shall be:

    1.  Serious illness or death in the immediate family

    2.  Serious illness of the member or new member

    3.  Representing the college or university officially

    4.  Meetings, examinations or interviews for future secondary programs of study with the confirmation of supporting documentation

    5.  Future employment/internship interview(s) with the confirmation of supporting documentation

    6.  Previously contracted employment that cannot be rescheduled

    7.  Study excuse: Two excuses shall be allowed per academic term. Study excuses may only be used for chapter and/or new member meetings for study purposes.

    8.  Personal absence: One personal absence shall be allowed per academic term.

        1.  A personal absence may only be used for a required Fraternity event or required chapter event.

            1.  A personal absence must be for a legitimate reason and approved by the Excuse Note Committee or Executive Council.”

For more information see Alpha Chapter Bylaws 2025
