---
title: "Directors & Newsletter"
format: html
---

## Directors

You will have 2 directors:

-   Director of Communications 

-   Director of Attendance 

    -   This is not the official name, you can have them do whatever you need them to do, attendance just happens to be a big job I needed help with

    -   Our chapter doesn’t use the “Director of Chapter History” as directed in the Administration Team Handbook, this director is replacing that

        -   The reason why we don't have the director of chapter history is most likely because our chapter recently made the jump from structure C to D in the past couple of years– feel free to explore these responsibilities if you want to include more in your position!

### Director of Communications

The biggest thing that the director of communications does is the newsletter, see below. For the official responsibilities of this director, see the Director of Communication information in the Admin Team Handbook. This is where you can also check the Director of History responsibilities, if you’re interested. 

### Director of Attendance

Like briefly stated above, the director of attendance is an extra director awarded to VP Admin in Spring 2025. You can make this position your own based on your needs! 

I recommend:

-   Having them help with attendance records (moving stuff from flare \> google drive/sheets) 

-   Having them help with excuses 

    -   This really depends on who your director is, excuses can be personal and must be handed with privacy 

-   Having them help do attendance, especially if you can’t make an event

-   For normal events, just give them the QR code

-   For recruitment, since I recommend doing manual attendance, you can tell them to bring their computer too to help with the process!

## Newsletter

The newsletter is sent out roughly every month to a list of our alumni. The purpose of this is to keep in contact with them and eventually to have a strong enough relationship with them to include a link for donations. 

The newsletter is on Canva, the link can be found here: [Newsletter](Butterfield_Bulletin.qmd)

You can put whatever you want to on the newsletter! I recommend: 

-   Asking at OB if anyone has anything they want to be included

-   Getting pictures from recent events 

-   Asking advisors/president if there is anything to share

-   Random pictures of sisterhood that will remind alumni of their time in the chapter
