---
title: "Roster Management"
format: html
---

## EC Meetings {.tabset}

EC (Executive Council) meetings are when the Exec. officers and all advisers meet. This needs to happen at least once a month, but you don’t need to worry about scheduling it yourself.

EC meetings are different from OB (Officer Board) meetings, which are only the collegiate members on Exec meetings without advisers. \

To prepare for **EC meetings** you need to prepare 2 things: 

-   Meeting Agenda

-   Meeting Minutes\

To prepare for **OB meetings** you still need to send Exec the meeting agenda, but you don’t need to send it to the advisers or take minutes. I recommend taking minutes anyways, but that is just me. You can only submit minutes from EC meetings, so if you do take OB minutes, make sure you know which minutes are which.

### Meeting Agenda

The meeting agenda will need to be sent in the Exec group chat early (ish) on Sunday Morning. The timing doesn’t need to be exactly the same every week, but time it so there are a couple hours before that week’s meeting to have it filled out. 

Around 1 hour before the meeting is planned to start, check the meeting agenda again. It more than likely was not filled out by every officer. Send a reminder text to the Exec group chat so people remember to fill it out. 

Around 30 minutes before the EC zoom, send the filled out (either entirely or mostly) agenda to the adviser group chat. 

### Meeting Minutes

The meeting minutes are important, as they are submitted to IHQ. There needs to be a copy of the meeting minutes for each month of the academic year submitted to them. Before the EC meetings, you can edit simple things like date/time with the template. During EC, you need to update the attendance and take minutes. For attendance, I just look at the names in the zoom. For minutes, update them with the level of information you believe is appropriate. 

I recommend keeping minutes for OB as well, as it is easier to remember to take them every meeting rather than keeping track of OB vs EC, but it is up to you!

You don’t need to send the minutes to anyone until you submit them to IHQ by the deadline. 

The deadline for submitting minutes is around the deadline for submitting good standing points, which varies year to year. It is often around the end of the academic semester, so in early December and late April. You can submit minutes every month, if it is easier to do so. You can also upload them all on the same day if that is best for you. 

Before or during EC/OB Meetings, you will have a copy of the slides to fill out for that day’s chapter (assuming you are attending a regular meeting on Sunday). Fill out your slide, but also ensure that you upload the most accurate flare QR code. 
