---
title: "Excuses & Attendance Records"
format: html
---

## Excuses

The way that you approve/deny excuses and keep attendance records is ultimately up to you and your EC. 

For excuse forms, I recommend: 

-   Sending them out roughly 2 weeks in advance of the event

-   Making them due roughly 1 week in advance of the event 

-   Posting the excusals 3-7 days before the event

    -   I usually do 2 or 3 days so people have time to text me 

If the excuse form is for someone else’s event, i.e. Philanthropy, I always sent it to them to have them review it before sending it to the chapter. This is OPTIONAL, I personally did this because I want to have someone else double check the date and time! \

You can format the excuse forms however you want/what works best for approving/denying excuses easily.  

What I recommend: 

-   I find having the information on one page and the questions on the next is the best way to have people read the information they would otherwise skip

-   Having first and last name as two different questions so you can do alphabetical order for either 

-   Having intentional options for members to select in terms of excuses (ie. “work” and “school”) 

    -   best for having a minimal number of invalid excuses submitted 

-   Having the option to submit multiple photos for proof 

Here is an example excuse form that I have based all my forms off of:  [Example Excuse Form](https://forms.gle/C2mx4kMod5KwRGsA7)

The types of excuses that are allowed are based on the type of event. More important events require stricter excuses. Review the [Alpha Chapter Accountability](https://docs.google.com/document/u/2/d/1vmihnQaY2EisEFW4f1FvatdKNZ68Z-IXpbE2tGNtwbY/edit) doc for more details. 

Do your best to follow the Bylaws as closely as you can. This ensures that excusals are uniform and fair across members, events, and reasons people are requesting to be excused. 

\

Ensure that you notify members of the deadlines for the excuses multiple ways. There is always someone that doesn’t listen and they will tell you that they didn’t know the form was due when it was. If you have various methods of communication, then you can tell that person that their late excuse isn’t valid with a more concrete explanation. 

\

What I recommend: 

-   Announcing at Chapter when you post the form

-   Announcing at Chapter when the form is due

-   Posting the excuse form in the same place every time (I do the chapter resource doc for easy access)

-   Posting the deadline under the link to the excuse form 

-   Announcing in Flare when you post the form

-   Announcing in Flare when the form is due 

-   Making a flare calendar event when the form is due

    -   with a link to the form 

    -   When the form is due 

    -   A reminder notification that goes off 10 minutes before it is due\

## Attendance Records

Ensure you keep records in writing, this way if there are any issues there is “proof.” It is up to you how to keep Attendance Records, however, according to my Spring 2025 feedback form, people preferred to have one large sheet/ Attendance Tracker rather than smaller sheets for each event. \

The way that you do attendance is different depending on the event. Review this fine outline to see how different events are fined. 

\
My recommendations: 

-   Recruitment: you stand at the door for check in and check out to ensure that everyone

-   is physically there. This is the chapter's MOST IMPORTANT event so although it is tedious I think this is important

    -   Recruitment is fined per party but you don’t need to worry about this, recruitment will very clearly know who is at each party 

    -   You will be working with someone from the recruitment team to do excuses and attendance… more to come

-   New Mem Events: Have one of the VPNME Directors do this

-   Random events (such as Panhel required events, philanthropy, etc.) have one of the Exec members going do attendance via flare

-   Most Events (Chapter, big/little, OUR philanthropy, etc.) use a flare QR code, opt in to do check in and check out if it is a really hefty fine / important event (our philanthropy)

-   Some events need hourly fines (retreat) it is up to you how you do attendance, I would do whatever is easiest

-   OPTIONAL: Alternative Attendance Form in case flare doesn’t work out

    -   There would be times peoples phone was dead/broken and they needed to checkout, I gave them my phone or had them borrow a friends

    -   Much more reliable than someone coming up to you after something and you having to remember (especially if you forget and then they get fined and then there is no way to actually prove they were there!

\
VP Finance will need to be able to easily access your attendance in order to give fines to people. Ensure that it is clear if someone was absent for this reason. 

\
