---
title: "Inactive Status"
format: html
---

There is also Inactive Status, which is part of the CIMS Manual but is different from the other statuses where you are changing the official chapter roster. Inactive status is a special status that members can apply for if they are unable to be a full member of the chapter. Examples include working full time/school, taking more credits, not enough time, etc. There are many reasons why someone may go inactive. \

Important things about inactive: 

-   People may only go inactive for ONE semester

    -   It is an option to go inactive for more semesters but it is in rare circumstances only 

-   People still have to go to RTS/Recruitment

-   They have to pay for merch if they want it 

-   They have to pay for date night and formal if they choose to attend

-   They have (slightly) decreased dues

-   EC must meet in order to vote to let someone be inactive

    -   You will send inactive paper work in advance, present their case to EC, and vote

-   Our chapter is just under 200 members as of now, this includes active, inactive, and abroad members 

    -   This means that the TOTAL number of inactive cases you can have in a given semester is no more than 10 

    -   Once we get more new members, this number may change, and then may change again when the seniors graduate, see the CIMS manual

Inactive Paperwork: [**\[There is a PDF you need to send\]**](https://drive.google.com/open?id=1A02YgHkY2LUOhuev3TQMKbsEccbEPH_u) This is what you will send to anyone wanting to go inactive. I suggest sending it over email as that is the chapter’s admin email and is 

1.  Taken more seriously 

2.  Better for keeping track of important, potentially confidential paperwork.

The document, and many other templates and documents you might need are in the Appendix of the CIMS manual. 

\
[Here is an example template of the email that I send when I reach out to people with inactive status paperwork:](Inactive_Email_Example.qmd)

Once they are approved/denied for inactive status you need to inform them of this change as soon as you can. There are templates in the CIMS manual, but I prefer to write in my own tone.

Once inactive, all you need to do for the member to be officially inactive is to update YOUR roster(s) with their new status and store their paperwork in an organized folder on the google drive, there is nothing to do in MyAlphaGam or with IHQ

More inactive status info: CIMS Manual

\
