---
title: "Miscellaneous"
format: html
---

## Non Mandatory Sisterhood Event

You need to have at least one non mandatory sisterhood event a semester. There is currently \$75 budgeted towards this. You can use that money for more than one event, or you can spend it all on one bigger event. 

The budget is reset in May, so spend all of your money before then. In the Fall, your budget is split between your fall and your incoming officer’s budget. 

You can come up with whatever event ideas you want! If you want to buy anything, you will need to fill out a PRV so the VP Finance can order the items for you. Reach out to VP Finance with more questions regarding this kind of stuff. 

## Fine Appeal Form

When fines are put in, members have the ability to fill out a fine appeal form to try to prove the fine is invalid. This is a responsibility shared with VP Finance. You will need to help approve/deny their proof that they upload to the form. VP Finance will then remove or keep the fine. 

## Chapter Meetings

For every chapter meeting, there is a couple of things that must be done: 

-   Chapter Excuses sorted and posted

-   Update the QR code for attendance on the chapter slides

-   Fill out your slide, if you have any announcements

-   Post the chapter slides to the chapter resource doc

-   Flare attendance filled out on your attendance sheet

## Office Hours

Last semester, Spring 2025, was the first semester that VP Admin had office hours ( I think). I wasn’t required to do them this semester, Fall 2025, due to a small number of events. I am unsure if you will need to do office hours. 

\
If you do have to do them, just pick one hour in the week that you can consistently be available for. Then you can just sit wherever you want in the house and people can come ask you whatever questions they need to ask.

## Be in Initiation

Technically, the only people in initiation are supposed to be President, Wellness, Academic, Recruitment, Membership. I am unsure why, but recently our chapter has had Admin do it instead of Membership. Maybe you will be in initiation, maybe not. 

## Chapter Resource Document

-   I would start by making a copy of the chapter resource doc as it currently is 

-   Update the name to the semester or year 

-   Update the link in Flare

The chapter resource doc is a good place to post anything important, there is no specific list of things that must be on the doc other than the bylaws, chapter slides, door code, fine appeal list, and other things you deem important.

## Things I Wanted to Implement, but Didn’t

No pressure to do any of these things, it is just an idea list

-   Chapter Wish List (Amazon?) on the newsletter for donations

-   Posting all of the excuses that are allowed for each event in a form called “common excuse guide”

-   Explore the roles of the Director of Chapter History \

## Last Bits

This isn’t relevant for you but the next admin after you need to rewrite the bylaws and submit them to the DAC committee by Feb 1st

I recommend you send out a feedback survey at the end of your spring semester to see what your position can change/improve in 

I prefer anonymous but if you think that people will hurt your feelings (they will be mean) then you can make it w name/email log in
