---
title: "Winter Break Tasks"
format: html
---

-   Don’t hesitate to reach out to me with any questions, it’s kinda a steep learning curve at first

-   Reach out to [Dana (Advisor)](https://docs.google.com/document/d/11bxnobmjtCDJVBwjfv-xIVjdLSBWeg1klrqL3rdfGsA/edit?tab=t.0#heading=h.bax678d3x7hk)

-   Recruitment Excuses sorted and posted. You will need to meet with the recruitment team to do this! 

-   Find out who is going abroad next spring, if not already done

-   I highly recommend making most or all of your excuse forms in advance, they can obviously be changed but it is annoying throughout the semester and there is usually more events in spring than in fall

-   Change the name on the admin email, create a personal signature

-   Change the password on the admin email 

-   Update your google drive rosters

    -   Who graduated (if anyone)?

    -   Who is abroad in the spring? 

    -   Move inactive and abroad members from Fall to the “Actives” roster

-   Approve any CIMS cases BEFORE January 1st

-   Submit any good standing stuff: EC Minutes from August, September, October, November, December (if possible)

-   Rachel Fain: Last semester she was home/away from school. She applied to be inactive but we put her on emergency alumnae status, she said she wanted to come back in the Spring, see how she is, reach out to Dana if you need more details, ultimately ensure she can come back to the chapter with a smooth transition

<!-- -->

-   Sarah Yoffe: She reached out to me in September 2025 about going inactive. She is worried about graduating on time if she doesn’t go inactive. She was also hoping to get out of recruitment, but she didn't know that inactives still have to be a part of recruitment. I directed her to Giuliana, who may or may not have excused her from

-   Come up with inactive email scripts etc. 

-   This is optional but I learned throughout my time that understanding what is in these documents (not necessary to memorize it) makes it easier to answer questions that you’re unsure about before you ask Dana (Advisor) or Ana (Pres) 

    -   Look through the:

        -   [Administration Team Handbook](https://alphagammadelta.sharepoint.com/:b:/g/Handbook/EY9HH8q4dE9IixDc0Oiku7IBUsZYw7IqDY_2g8BgZRNWBg?e=lEoClN)

        -   [Change in Membership Status Manual](https://alphagammadelta.sharepoint.com/:b:/g/Handbook/ESusAs4EV89Eg9eu7ZXFY24BRkQRgwDMLxf7-XEt6Ah5BA?e=rNvI9y)

        -   Alpha Chapter Bylaws
